### ISSUE TITLE
Question : Return full Inventory

### ISSUE THREAD

**Issue by WIwish** [sebmorris/steam-inventory-api#1]
Hi and thanks for your great jobs !

I'm trying to use the basic.js example to return list of all my cards.
I put my steamID and modify the console output :
`steamInventoryContents('76561198038092362', 753, 6, true)
.then((inventory) => {
	console.log(inventory);
})
.catch((err) => {
	//Logs out any error
	console.log('Error '+err);
});`

It's return me only the 100 first tradable items, then output say "... 5393 more items ]".

How can I have the full output ?

Thanks !

**Comment by sebmorris** [comment]
You can loop over inventory and print out each item individually.

`inventory.forEach(item => console.log(item));`
